# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'selenium-webdriver'
gem 'rspec'
gem 'ffi'
gem 'webdrivers'
gem 'russian', '~> 0.6.0'
gem 'cucumber'